-- учебники, их индекс и разбор домашки нейросетью
-- индекс лёгкий: страница, тема, какие упражнения на ней лежат
-- координаты заданий сюда не пишем, они считаются лениво при первой выдаче
-- и оседают в textbook_boxes, так индекс дешевле и точность кропа выше


-- сама книга, pdf лежит на диске по pdf_path
CREATE TABLE IF NOT EXISTS textbooks (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_class         VARCHAR(32),
    subject             VARCHAR(256) NOT NULL,
    grade               INTEGER,
    title               VARCHAR(512),
    authors             VARCHAR(512),
    part                VARCHAR(32),
    kind                VARCHAR(16)  NOT NULL DEFAULT 'textbook'
        CHECK (kind IN ('textbook', 'workbook', 'other')),
    pdf_path            VARCHAR(512) NOT NULL,
    page_count          INTEGER      NOT NULL DEFAULT 0,
    -- печатный номер страницы минус её индекс в pdf, считаем по медиане колонтитулов
    printed_offset      INTEGER      NOT NULL DEFAULT 0,
    status              VARCHAR(16)  NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'indexing', 'ready', 'failed')),
    status_detail       TEXT,
    indexed_pages       INTEGER      NOT NULL DEFAULT 0,
    index_version       INTEGER      NOT NULL DEFAULT 1,
    uploaded_by_prs_id  INTEGER,
    created_at          TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at          TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_textbooks_lookup
    ON textbooks (grade_class, subject, status);

DROP TRIGGER IF EXISTS trg_textbooks_touch ON textbooks;
CREATE TRIGGER trg_textbooks_touch
    BEFORE UPDATE ON textbooks
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


-- что лежит на странице, по этому ищем задания без номера, по теме
CREATE TABLE IF NOT EXISTS textbook_pages (
    textbook_id      BIGINT       NOT NULL
        REFERENCES textbooks (id) ON DELETE CASCADE,
    pdf_index        INTEGER      NOT NULL,
    printed_page     INTEGER,
    page_kind        VARCHAR(16),
    paragraph_num    VARCHAR(32),
    paragraph_title  VARCHAR(512),
    topic_summary    TEXT,
    rules            JSONB,
    PRIMARY KEY (textbook_id, pdf_index)
);

CREATE INDEX IF NOT EXISTS idx_textbook_pages_paragraph
    ON textbook_pages (textbook_id, paragraph_num);


-- на какой странице какое упражнение
-- starts_here=false значит сюда попал только хвост с предыдущей страницы
CREATE TABLE IF NOT EXISTS textbook_exercises (
    textbook_id          BIGINT      NOT NULL
        REFERENCES textbooks (id) ON DELETE CASCADE,
    label                VARCHAR(32) NOT NULL,
    pdf_index            INTEGER     NOT NULL,
    starts_here          BOOLEAN     NOT NULL DEFAULT TRUE,
    continues_next_page  BOOLEAN     NOT NULL DEFAULT FALSE,
    PRIMARY KEY (textbook_id, label, pdf_index)
);

CREATE INDEX IF NOT EXISTS idx_textbook_exercises_label
    ON textbook_exercises (textbook_id, label);


-- границы задания на странице, считаются один раз и живут вечно:
-- упражнение 245 не переезжает, второй раз за него платить незачем
CREATE TABLE IF NOT EXISTS textbook_boxes (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    textbook_id  BIGINT       NOT NULL
        REFERENCES textbooks (id) ON DELETE CASCADE,
    label        VARCHAR(32)  NOT NULL,
    -- пустая строка это всё задание целиком, иначе конкретный пункт
    subitem      VARCHAR(16)  NOT NULL DEFAULT '',
    pdf_index    INTEGER      NOT NULL,
    box          JSONB        NOT NULL,
    tails        JSONB,
    subitems     JSONB,
    image_path   VARCHAR(512),
    created_at   TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    UNIQUE (textbook_id, label, subitem)
);


-- разбор домашки, одна строка на класс, а не на каждого ученика:
-- монитор обходит регистрации по одной, без дедупа класс из 25 человек
-- посчитал бы одно и то же 25 раз
CREATE TABLE IF NOT EXISTS homework_analysis (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dedup_hash     VARCHAR(64)  NOT NULL UNIQUE,
    grade_class    VARCHAR(32)  NOT NULL,
    subject        VARCHAR(256) NOT NULL,
    lesson_date    DATE,
    source         VARCHAR(16)  NOT NULL DEFAULT 'teacher'
        CHECK (source IN ('teacher', 'custom')),
    source_id      VARCHAR(64),
    raw_text       TEXT         NOT NULL,
    status         VARCHAR(16)  NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'done', 'failed', 'rejected')),
    -- почему своя домашка не доехала до одноклассников: бред или дубль
    reject_reason  VARCHAR(16),
    reject_detail  TEXT,
    duplicate_of   BIGINT       REFERENCES homework_analysis (id) ON DELETE SET NULL,
    textbook_id    BIGINT       REFERENCES textbooks (id) ON DELETE SET NULL,
    targets        JSONB,
    items          JSONB,
    total_minutes  INTEGER,
    range_min      INTEGER,
    range_max      INTEGER,
    hardest        VARCHAR(128),
    why            TEXT,
    attempts       INTEGER      NOT NULL DEFAULT 0,
    last_error     TEXT,
    created_at     TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at     TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_homework_analysis_feed
    ON homework_analysis (grade_class, lesson_date, subject);
CREATE INDEX IF NOT EXISTS idx_homework_analysis_status
    ON homework_analysis (status, created_at);

DROP TRIGGER IF EXISTS trg_homework_analysis_touch ON homework_analysis;
CREATE TRIGGER trg_homework_analysis_touch
    BEFORE UPDATE ON homework_analysis
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


-- вырезанные из учебника картинки заданий
CREATE TABLE IF NOT EXISTS homework_analysis_images (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id   BIGINT       NOT NULL
        REFERENCES homework_analysis (id) ON DELETE CASCADE,
    label         VARCHAR(32)  NOT NULL,
    subitem       VARCHAR(16)  NOT NULL DEFAULT '',
    target_type   VARCHAR(16)  NOT NULL DEFAULT 'exercise',
    printed_page  INTEGER,
    storage_path  VARCHAR(512) NOT NULL,
    sort_order    INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_homework_analysis_images_analysis
    ON homework_analysis_images (analysis_id, sort_order);


-- пуш ждёт разбора: уведомление уходит уже с оценкой времени и сложности
-- одну и ту же домашку ловят несколько регистраций, разбор общий, а пуши личные
CREATE TABLE IF NOT EXISTS pending_notifications (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    analysis_id             BIGINT       NOT NULL
        REFERENCES homework_analysis (id) ON DELETE CASCADE,
    audience                VARCHAR(16)  NOT NULL
        CHECK (audience IN ('registration', 'class', 'group')),
    registration_id         VARCHAR(64),
    grade_class             VARCHAR(32),
    title                   VARCHAR(256) NOT NULL,
    body                    TEXT,
    data                    JSONB,
    payload                 JSONB,
    exclude_classmate_id    VARCHAR(64),
    exclude_registration_id VARCHAR(64),
    status                  VARCHAR(16)  NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sent', 'dropped')),
    created_at              TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    sent_at                 TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pending_notifications_analysis
    ON pending_notifications (analysis_id, status);
-- по нему сторож ищет пуши, застрявшие из за упавшего разбора
CREATE INDEX IF NOT EXISTS idx_pending_notifications_stale
    ON pending_notifications (status, created_at);


-- очередь тяжёлых задач для нейросети, воркер разбирает её отдельным процессом
CREATE TABLE IF NOT EXISTS ai_jobs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        VARCHAR(32) NOT NULL,
    dedup_key   VARCHAR(128),
    payload     JSONB       NOT NULL,
    status      VARCHAR(16) NOT NULL DEFAULT 'queued'
        CHECK (status IN ('queued', 'running', 'done', 'failed')),
    attempts    INTEGER     NOT NULL DEFAULT 0,
    last_error  TEXT,
    locked_at   TIMESTAMP,
    locked_by   VARCHAR(64),
    run_after   TIMESTAMP   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    created_at  TIMESTAMP   NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at  TIMESTAMP   NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);

CREATE INDEX IF NOT EXISTS idx_ai_jobs_pick
    ON ai_jobs (status, run_after);
-- один и тот же разбор не ставим в очередь дважды
CREATE UNIQUE INDEX IF NOT EXISTS idx_ai_jobs_dedup
    ON ai_jobs (dedup_key) WHERE dedup_key IS NOT NULL AND status IN ('queued', 'running');

DROP TRIGGER IF EXISTS trg_ai_jobs_touch ON ai_jobs;
CREATE TRIGGER trg_ai_jobs_touch
    BEFORE UPDATE ON ai_jobs
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
