-- сводка урока: когда на один слот пришло несколько записей (учитель плюс
-- одноклассник, или двое одноклассников), показываем их одной карточкой
-- сводка это производное представление, а не слияние записей: оригиналы никто
-- не трогает. поэтому удаление и правку не надо разматывать, достаточно
-- пересобрать сводку из того, что осталось

CREATE TABLE IF NOT EXISTS homework_merge (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grade_class   VARCHAR(32)  NOT NULL,
    subject       VARCHAR(256) NOT NULL,
    lesson_date   DATE         NOT NULL,
    -- хэш состава: совпал, значит пересобирать нечего
    parts_hash    VARCHAR(64),
    merged_text   TEXT,
    authors       JSONB,
    highlights    JSONB,
    part_count    INTEGER      NOT NULL DEFAULT 0,
    status        VARCHAR(16)  NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'ready', 'failed', 'empty')),
    last_error    TEXT,
    created_at    TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at    TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    UNIQUE (grade_class, subject, lesson_date)
);

DROP TRIGGER IF EXISTS trg_homework_merge_touch ON homework_merge;
CREATE TRIGGER trg_homework_merge_touch
    BEFORE UPDATE ON homework_merge
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


-- из чего собрана сводка, пересобираем по этому списку
CREATE TABLE IF NOT EXISTS homework_merge_parts (
    merge_id     BIGINT      NOT NULL
        REFERENCES homework_merge (id) ON DELETE CASCADE,
    analysis_id  BIGINT      NOT NULL
        REFERENCES homework_analysis (id) ON DELETE CASCADE,
    source       VARCHAR(16) NOT NULL,
    author       VARCHAR(256),
    sort_order   INTEGER     NOT NULL DEFAULT 0,
    PRIMARY KEY (merge_id, analysis_id)
);

CREATE INDEX IF NOT EXISTS idx_homework_merge_parts_analysis
    ON homework_merge_parts (analysis_id);
