CREATE TABLE telegram_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_key CHAR(64) NOT NULL,
    event_scope CHAR(64) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    payload_encrypted TEXT NOT NULL,
    progress_encrypted TEXT,
    notification_type VARCHAR(32),
    source_id VARCHAR(128),
    status VARCHAR(16) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'sending', 'retry', 'sent', 'failed', 'unknown')),
    attempts INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    locked_until TIMESTAMP,
    last_error JSONB,
    created_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    sent_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);
CREATE INDEX telegram_outbox_due ON telegram_outbox (next_attempt_at, id)
    WHERE status IN ('pending', 'retry');
CREATE INDEX telegram_outbox_scope ON telegram_outbox (event_scope, id DESC);
CREATE INDEX telegram_outbox_target ON telegram_outbox (target_key, id)
    WHERE status IN ('pending', 'sending', 'retry');
ALTER TABLE pending_notifications ADD COLUMN delivery_attempts INTEGER NOT NULL DEFAULT 0;
